export const initialValues = {
  name: "",
  username: "",
  designation: "",
  city: "",
  state: "",
  joiningDate: "",
  password: "",
  confirmPassword: "",
  phoneNumber: "",
  code: "",
  role: "admin",
  department: "",
  pic: { file: [] },
};
